#ifndef MATCHING_GLOBAL_H
#define MATCHING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATCHING_LIBRARY)
#  define MATCHINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MATCHINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MATCHING_GLOBAL_H
