#ifndef FEATUREEXTRACTION_GLOBAL_H
#define FEATUREEXTRACTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FEATUREEXTRACTION_LIBRARY)
#  define FEATUREEXTRACTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FEATUREEXTRACTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FEATUREEXTRACTION_GLOBAL_H
